version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: gemini_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gemini_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  celery:
    build: .
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/gemini_db
      - REDIS_URL=redis://redis:6379
    volumes:
      - .:/app
    command: celery -A app.tasks.gemini_tasks worker --loglevel=info

volumes:
  postgres_data: